apiVersion: v1
kind: Service
metadata:
    name: "samplecenter-0221"
    labels:
        app: "samplecenter-0221"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "samplecenter-0221"